# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: INFO
        sn.sonatel.dsi.dif.selfcare.b2c: INFO
        io.github.jhipster: INFO

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@10.100.97.175:8761/eureka/

spring:
    profiles:
        active: uat
        include:
        - swagger
        - chron
        #- liquibase
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://10.100.97.175:3306/selfcare_b2c_account_management?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: Son@tel2019
        hikari:
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.BeanClassLoaderAwareJCacheRegionFactory

    liquibase:
        contexts: uat
    mail:
        host: 10.100.56.56
        port: 25
        username:
        password:
    thymeleaf:
        cache: true
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://10.137.52.11:9411
        enabled: true
        locator:
            discovery:
                enabled: true

# ===================================================================
# To enable TLS in production, generate a certificate using:
# keytool -genkey -alias selfcare-b2c-account-management -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: classpath:config/tls/keystore.p12
#        key-store-password: password
#        key-store-type: PKCS12
#        key-alias: selfcare-b2c-account-management
#        # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#        ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
server:
    port: @server.port.docker.expose@
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 1000 # Number of objects in each cache entry
    security:
        client-authorization:
            access-token-uri: http://selfcare-b2c-uaa/oauth/token
            token-service-id: selfcare-b2c-uaa
            client-id: internal
            client-secret: internal
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: selfcare-b2c-account-management@localhost
        base-url: http://my-server-url-to-change # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: true
            host: 10.137.52.11
            port: 5000
            queue-size: 512
oauth2:
    signature-verification:
        public-key-endpoint-uri: http://selfcare-b2c-uaa/oauth/token_key
        #ttl for public keys to verify JWT tokens (in ms)
        ttl: 3600000
        #max. rate at which public keys will be fetched (in ms)
        public-key-refresh-rate-limit: 10000
    web-client-configuration:
        #change client secret in production, keep in sync with UAA configuration
        client-id: web_app
        secret: changeit

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
application:
    max-attempts: 3
    authentication-authorisation-user-server-host: http://selfcare-b2c-uaa
    url-otp: http://selfcare-otp
    lien-ibou: #https://m.me/165622776799685
    email-service-client-orange: fatou.diaw@orange-sonatel.com

    api-management:
        auth:
            grant_type: client_credentials
            client_id: selfcare-b2c
            client_secret: a041ac00-e18b-4a3a-aeb7-a53a0856c5fd
            key-access-token-uri: https://iaam.orange-sonatel.com/auth/realms/apimanagement/protocol/openid-connect/token
        url-api:
            base-name: api-accountmanagement
            base-url: https://api.orange-sonatel.com
            url-account-management: /api-accountmanagement
        party-management:
            name: api-partymanagement
            url-individual-information: /api/partyManagement/v1/individual/{msisdn}
            url-organization-information: /api/partyManagement/v1/organization/{msisdn}

    message-block-user: L acces a votre compte Orange et moi a ete bloque, cliquez sur mot de passe oublie et suivez les instructions
    service-client-orange: . Service Client Orange

    selfcare-mail:
        sender-address: mailer.orangeetmoi@orange-sonatel.com
        sender-name: Orange et Moi
        mail-subject: Orange et Moi
    urgence-depannage:
        operation:
            -
                code: operation-100
                title: Deplafonnement de compte Orange Money
            -
                code: operation-200
                title: Ouverture de compte Orange Money
            -
                code: operation-300
                title: Erreur transaction Orange Money
    send-sms:
        sponsorship:
            sms-sponsee: Bonjour, Comme moi telecharge l'appli Orange et Moi et retrouve tous tes services Orange en quelques clics. %s FI rek la http://bit.ly/2NHn5aS ou sur www.orangeetmoi.sn
            sms-sponsor: Bonjour, le numero %s que vous avez parraine s est inscrit sur l'appli Orange et Moi. Continue a inviter tes proches.
            sms-promo: Fais le aujourd hui et gagne %s %s.
    scheduler:
        cron-disabled-sponsee: 0 00 00 * * ?

    hmac-secret: secretToShareWithGatewayOM

    serveur-ftp:
        port: 22
        user: portailomsftp
        password: Port@ilomsftp0279
        ip-serveur: 10.137.56.3
        directory: /directory/

    tmp-path: /var/tmp/

log-manager:
    microservice-name: Account Management
    app-name: Selfcare B2C



