# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        io.github.jhipster: DEBUG
        sn.sonatel.dsi.dif.selfcare.b2c: DEBUG

eureka:
    instance:
        prefer-ip-address: true
        ip-address: @eureka.instance.dev.hostname@
        hostname: @eureka.instance.dev.hostname@
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@10.100.59.111:8761/eureka/

spring:
    profiles:
        active: dev
        include:
        - swagger
        - chron
        # Uncomment to activate TLS for the dev profile
        #- tls
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://10.137.52.11:3305/selfcare_b2c_account_management?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: digitalfactory
        hikari:
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.BeanClassLoaderAwareJCacheRegionFactory

    liquibase:
        contexts: dev
    mail:
        host: 10.100.56.56
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true

server:
    port: @server.port.docker.expose@

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need to activate TLS (see application-tls.yml)
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 100 # Number of objects in each cache entry
        # CORS is disabled by default on microservices, as you should access them through a gateway.
        # If you want to enable it, please uncomment the configuration below.
        # cors:
        # allowed-origins: "*"
        # allowed-methods: "*"
        # allowed-headers: "*"
        # exposed-headers: "Authorization,Link,X-Total-Count"
        # allow-credentials: true
        # max-age: 1800
    security:
        client-authorization:
            access-token-uri: http://selfcare-uaa/oauth/token
            token-service-id: selfcare-uaa
            client-id: internal
            client-secret: internal
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: selfcare-b2c-account-management@localhost
        base-url: http://127.0.0.1:8707
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
oauth2:
    signature-verification:
        public-key-endpoint-uri: http://selfcare-uaa/oauth/token_key
        #ttl for public keys to verify JWT tokens (in ms)
        ttl: 3600000
        #max. rate at which public keys will be fetched (in ms)
        public-key-refresh-rate-limit: 10000
    web-client-configuration:
        #keep in sync with UAA configuration
        client-id: web_app
        secret: changeit

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
application:
    max-attempts: 3
    authentication-authorisation-user-server-host: http://selfcare-uaa
    url-otp: http://selfcare-otp
    lien-ibou: #https://m.me/165622776799685
    email-service-client-orange: fatou.diaw@orange-sonatel.com

    api-management:
        auth:
            grant_type: client_credentials
            client_id: selfcare-b2c
            client_secret: a041ac00-e18b-4a3a-aeb7-a53a0856c5fd
            key-access-token-uri: https://iaam.orange-sonatel.com/auth/realms/apimanagement/protocol/openid-connect/token
        url-api:
            base-name: api-accountmanagement
            base-url: https://api.orange-sonatel.com
            url-account-management: /api-accountmanagement
            url-party-management: /api-partymanagement
        api-name:
            party-management: api-partymanagement


    message-block-user: L acces a votre compte Orange et moi a ete bloque, cliquez sur mot de passe oublie et suivez les instructions
    service-client-orange: . Service Client Orange

    selfcare-mail:
        sender-address: mailer.orangeetmoi@orange-sonatel.com
        sender-name: Orange et Moi
        mail-subject: Orange et Moi
    urgence-depannage:
        operation:
            -
                code: operation-100
                title: Deplafonnement de compte Orange Money
            -
                code: operation-200
                title: Ouverture de compte Orange Money
            -
                code: operation-300
                title: Erreur transaction Orange Money

    send-sms:
        sponsorship:
            sms-sponsee: Bonjour, Comme moi telecharge l'appli Orange et Moi et retrouve tous tes services Orange en quelques clics. %s FI rek la http://bit.ly/2NHn5aS ou sur www.orangeetmoi.sn
            sms-sponsor: Bonjour, le numero %s que vous avez parraine s est inscrit sur l'appli Orange et Moi. Continue a inviter tes proches.
            sms-promo: Fais le aujourd hui et gagne %s %s.
    scheduler:
        cron-disabled-sponsee: 0 00 00 * * ?

log-manager:
    microservice-name: Account Management
    app-name: Selfcare B2C



