/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package sn.sonatel.dsi.dif.selfcare.b2c.service.client.api;


import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import sn.sonatel.dsi.dif.selfcare.b2c.service.client.model.CustomerOffer;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-01T13:22:16.481+02:00")

@Api(value = "CustomerOffer", description = "the CustomerOffer API")
public interface CustomerOfferApi {

    @RequestMapping(value = "/api/accountManagement/v1/customerOffer/{msisdn}",
        produces = "*/*",
        consumes = "application/json",
        method = RequestMethod.GET)
    ResponseEntity<CustomerOffer> customerOffer(@ApiParam(value = "End User Id", required = true) @PathVariable("msisdn") String msisdn);

}
