/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package sn.sonatel.dsi.dif.selfcare.b2c.service.client.api;


import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import sn.sonatel.dsi.dif.selfcare.b2c.service.client.model.CustomerOffer;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-01T13:22:16.481+02:00")

@Api(value = "CustomerOffer", description = "the CustomerOffer API")
public interface CustomerOfferApi {


    @ApiOperation(value = "CustomerOffer", notes = "This operation get customer offers by msisdn. Attribute selection is enabled for all first level attributes. Filtering may be available depending on the compliance level supported by an implementation.  Specific business errors for current operation will be encapsulated in  HTTP Response 422 Unprocessable entity ", response = CustomerOffer.class, tags={ "Customer Offer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerOffer.class),
        @ApiResponse(code = 400, message = "Bad Request List of supported error codes: - 20: Invalid URL parameter value - 21: Missing body - 22: Invalid body - 23: Missing body field - 24: Invalid body field - 25: Missing header - 26: Invalid header value - 27: Missing query-string parameter - 28: Invalid query-string parameter value", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found  List of supported error codes: - 60 : Resource not found", response = Void.class),
        @ApiResponse(code = 405, message = "Method Not Allowed", response = Void.class),
        @ApiResponse(code = 422, message = "Unprocessable entity List of supported error codes: - 50 : Request cannot be processed", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/api/accountManagement/v1/customerOffer/{msisdn}",
        produces = "*/*",
        consumes = "application/json",
        method = RequestMethod.GET)
    ResponseEntity<CustomerOffer> customerOffer(@ApiParam(value = "End User Id", required = true) @PathVariable("msisdn") String msisdn);

}
